# Generated by Django 4.2.3 on 2023-08-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clasificacion',
            fields=[
                ('idclasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('ubicacion', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('rolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.rol')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('precio', models.FloatField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('idclasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clasificacion')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
