# Generated by Django 4.2.3 on 2023-08-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iduser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventario.usuario'),
        ),
    ]
